// Generated by Wrangler by running `wrangler types`

interface Env {
	SESSION_SECRET: string;
	VITE_LINE_CLIENT_ID: string;
	VITE_LINE_CLIENT_SECRET: string;
	VITE_LINE_CALLBACK_URL: string;
	VITE_LINE_LOGIN_BASE_URL: string;
	VITE_LINE_TOKEN_BASE_URL: string;
	VITE_LINE_PROFILE_BASE_URL: string;
	SUPABASE_URL: string;
	SUPABASE_ANON_KEY: string;
}
