// Generated by Wrangler by running `wrangler types`

interface Env {
	APP_ENV: string;
	APP_VERSION: string;
	SESSION_SECRET: string;
	VITE_LINE_CLIENT_ID: string;
	VITE_LINE_CLIENT_SECRET: string;
	VITE_LINE_CALLBACK_URL: string;
	VITE_LINE_LOGIN_BASE_URL: string;
	VITE_LINE_TOKEN_BASE_URL: string;
	VITE_LINE_PROFILE_BASE_URL: string;
	SUPABASE_URL: string;
	SUPABASE_ANON_KEY: string;
	DATABASE_URL: string;
	CLOUDFLARE_API_TOKEN: string;
	CLOUDFLARE_ACCOUNT_ID: string;
}
